spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 11111111
mybatis:
  type-aliases-package: com.yao.mybatis.entity
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
